//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace Cox.Wotl.ServiceManagementPlatform {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class ITVResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ITVReturnCode;
        
        /// <remarks/>
        public string ITVReturnMsg;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProvisionPin", typeof(ITVResponseProvisionPin))]
        [System.Xml.Serialization.XmlElementAttribute("GetEmailProperties", typeof(ITVResponseGetEmailProperties))]
        [System.Xml.Serialization.XmlElementAttribute("GetEmailInfo2", typeof(ITVResponseGetEmailInfo2))]
        public object Item;
    }
    
    /// <remarks/>
    public class ITVResponseProvisionPin {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ReturnCode;
        
        /// <remarks/>
        public string ReturnMsg;
    }
    
    /// <remarks/>
    public class ITVResponseGetEmailProperties {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ReturnCode;
        
        /// <remarks/>
        public string ReturnMsg;
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public string PinNumber;
        
        /// <remarks/>
        public string EmailPassword;
        
        /// <remarks/>
        public string POPServer;
        
        /// <remarks/>
        public string SMTPServer;
    }
    
    /// <remarks/>
    public class ITVResponseGetEmailInfo2EmailInfo2 {
        
        /// <remarks/>
        public string EmailAddress;
        
        /// <remarks/>
        public bool ParentFlag;
        
        /// <remarks/>
        public bool PinExists;
    }
    
    /// <remarks/>
    public class ITVResponseGetEmailInfo2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ReturnCode;
        
        /// <remarks/>
        public string ReturnMsg;
        
        /// <remarks/>
        public bool SuspendFlag;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailInfo2")]
        public ITVResponseGetEmailInfo2EmailInfo2[] EmailInfo2;
    }
}
