//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Cox.DataAccess.Enterprise {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class CarrierSchema : DataSet {
        
        private CarriersDataTable tableCarriers;
        
        public CarrierSchema() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected CarrierSchema(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Carrier"] != null)) {
                    this.Tables.Add(new CarriersDataTable(ds.Tables["Carrier"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CarriersDataTable Carriers {
            get {
                return this.tableCarriers;
            }
        }
        
        public override DataSet Clone() {
            CarrierSchema cln = ((CarrierSchema)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Carrier"] != null)) {
                this.Tables.Add(new CarriersDataTable(ds.Tables["Carrier"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableCarriers = ((CarriersDataTable)(this.Tables["Carrier"]));
            if ((this.tableCarriers != null)) {
                this.tableCarriers.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "CarrierSchema";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/CarrierSchema.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableCarriers = new CarriersDataTable();
            this.Tables.Add(this.tableCarriers);
        }
        
        private bool ShouldSerializeCarriers() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void CarrierChangeEventHandler(object sender, CarrierChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CarriersDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnCarrierId;
            
            private DataColumn columnName;
            
            internal CarriersDataTable() : 
                    base("Carrier") {
                this.InitClass();
            }
            
            internal CarriersDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn CarrierIdColumn {
                get {
                    return this.columnCarrierId;
                }
            }
            
            internal DataColumn NameColumn {
                get {
                    return this.columnName;
                }
            }
            
            public Carrier this[int index] {
                get {
                    return ((Carrier)(this.Rows[index]));
                }
            }
            
            public event CarrierChangeEventHandler CarrierChanged;
            
            public event CarrierChangeEventHandler CarrierChanging;
            
            public event CarrierChangeEventHandler CarrierDeleted;
            
            public event CarrierChangeEventHandler CarrierDeleting;
            
            public void AddCarrier(Carrier row) {
                this.Rows.Add(row);
            }
            
            public Carrier AddCarrier(string CarrierId, string Name) {
                Carrier rowCarrier = ((Carrier)(this.NewRow()));
                rowCarrier.ItemArray = new object[] {
                        CarrierId,
                        Name};
                this.Rows.Add(rowCarrier);
                return rowCarrier;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                CarriersDataTable cln = ((CarriersDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new CarriersDataTable();
            }
            
            internal void InitVars() {
                this.columnCarrierId = this.Columns["CarrierId"];
                this.columnName = this.Columns["Name"];
            }
            
            private void InitClass() {
                this.columnCarrierId = new DataColumn("CarrierId", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCarrierId);
                this.columnName = new DataColumn("Name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnName);
            }
            
            public Carrier NewCarrier() {
                return ((Carrier)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new Carrier(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(Carrier);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CarrierChanged != null)) {
                    this.CarrierChanged(this, new CarrierChangeEvent(((Carrier)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CarrierChanging != null)) {
                    this.CarrierChanging(this, new CarrierChangeEvent(((Carrier)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CarrierDeleted != null)) {
                    this.CarrierDeleted(this, new CarrierChangeEvent(((Carrier)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CarrierDeleting != null)) {
                    this.CarrierDeleting(this, new CarrierChangeEvent(((Carrier)(e.Row)), e.Action));
                }
            }
            
            public void RemoveCarrier(Carrier row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Carrier : DataRow {
            
            private CarriersDataTable tableCarriers;
            
            internal Carrier(DataRowBuilder rb) : 
                    base(rb) {
                this.tableCarriers = ((CarriersDataTable)(this.Table));
            }
            
            public string CarrierId {
                get {
                    try {
                        return ((string)(this[this.tableCarriers.CarrierIdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCarriers.CarrierIdColumn] = value;
                }
            }
            
            public string Name {
                get {
                    try {
                        return ((string)(this[this.tableCarriers.NameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCarriers.NameColumn] = value;
                }
            }
            
            public bool IsCarrierIdNull() {
                return this.IsNull(this.tableCarriers.CarrierIdColumn);
            }
            
            public void SetCarrierIdNull() {
                this[this.tableCarriers.CarrierIdColumn] = System.Convert.DBNull;
            }
            
            public bool IsNameNull() {
                return this.IsNull(this.tableCarriers.NameColumn);
            }
            
            public void SetNameNull() {
                this[this.tableCarriers.NameColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class CarrierChangeEvent : EventArgs {
            
            private Carrier eventRow;
            
            private DataRowAction eventAction;
            
            public CarrierChangeEvent(Carrier row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public Carrier Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
