//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Cox.DataAccess.Enterprise {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class MethodOfPaymentSchema : DataSet {
        
        private MethodsOfPaymentDataTable tableMethodsOfPayment;
        
        private tblApplicationGroupDataTable tabletblApplicationGroup;
        
        private tblPaymentTypeDataTable tabletblPaymentType;
        
        private DataRelation relationtblApplicationGrouptblMethodOfPaymentMap;
        
        private DataRelation relationtblPaymentTypetblMethodOfPaymentMap;
        
        public MethodOfPaymentSchema() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected MethodOfPaymentSchema(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblMethodOfPaymentMap"] != null)) {
                    this.Tables.Add(new MethodsOfPaymentDataTable(ds.Tables["tblMethodOfPaymentMap"]));
                }
                if ((ds.Tables["tblApplicationGroup"] != null)) {
                    this.Tables.Add(new tblApplicationGroupDataTable(ds.Tables["tblApplicationGroup"]));
                }
                if ((ds.Tables["tblPaymentType"] != null)) {
                    this.Tables.Add(new tblPaymentTypeDataTable(ds.Tables["tblPaymentType"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MethodsOfPaymentDataTable MethodsOfPayment {
            get {
                return this.tableMethodsOfPayment;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblApplicationGroupDataTable tblApplicationGroup {
            get {
                return this.tabletblApplicationGroup;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tblPaymentTypeDataTable tblPaymentType {
            get {
                return this.tabletblPaymentType;
            }
        }
        
        public override DataSet Clone() {
            MethodOfPaymentSchema cln = ((MethodOfPaymentSchema)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tblMethodOfPaymentMap"] != null)) {
                this.Tables.Add(new MethodsOfPaymentDataTable(ds.Tables["tblMethodOfPaymentMap"]));
            }
            if ((ds.Tables["tblApplicationGroup"] != null)) {
                this.Tables.Add(new tblApplicationGroupDataTable(ds.Tables["tblApplicationGroup"]));
            }
            if ((ds.Tables["tblPaymentType"] != null)) {
                this.Tables.Add(new tblPaymentTypeDataTable(ds.Tables["tblPaymentType"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableMethodsOfPayment = ((MethodsOfPaymentDataTable)(this.Tables["tblMethodOfPaymentMap"]));
            if ((this.tableMethodsOfPayment != null)) {
                this.tableMethodsOfPayment.InitVars();
            }
            this.tabletblApplicationGroup = ((tblApplicationGroupDataTable)(this.Tables["tblApplicationGroup"]));
            if ((this.tabletblApplicationGroup != null)) {
                this.tabletblApplicationGroup.InitVars();
            }
            this.tabletblPaymentType = ((tblPaymentTypeDataTable)(this.Tables["tblPaymentType"]));
            if ((this.tabletblPaymentType != null)) {
                this.tabletblPaymentType.InitVars();
            }
            this.relationtblApplicationGrouptblMethodOfPaymentMap = this.Relations["tblApplicationGrouptblMethodOfPaymentMap"];
            this.relationtblPaymentTypetblMethodOfPaymentMap = this.Relations["tblPaymentTypetblMethodOfPaymentMap"];
        }
        
        private void InitClass() {
            this.DataSetName = "MethodOfPaymentSchema";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/MethodOfPaymentSchema.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableMethodsOfPayment = new MethodsOfPaymentDataTable();
            this.Tables.Add(this.tableMethodsOfPayment);
            this.tabletblApplicationGroup = new tblApplicationGroupDataTable();
            this.Tables.Add(this.tabletblApplicationGroup);
            this.tabletblPaymentType = new tblPaymentTypeDataTable();
            this.Tables.Add(this.tabletblPaymentType);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("tblApplicationGrouptblMethodOfPaymentMap", new DataColumn[] {
                        this.tabletblApplicationGroup.grpIdColumn}, new DataColumn[] {
                        this.tableMethodsOfPayment.ApplicationGroupIdColumn});
            this.tableMethodsOfPayment.Constraints.Add(fkc);
            fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
            fkc.DeleteRule = System.Data.Rule.Cascade;
            fkc.UpdateRule = System.Data.Rule.Cascade;
            fkc = new ForeignKeyConstraint("tblPaymentTypetblMethodOfPaymentMap", new DataColumn[] {
                        this.tabletblPaymentType.paytpIDColumn}, new DataColumn[] {
                        this.tableMethodsOfPayment.PaymentTypeIdColumn});
            this.tableMethodsOfPayment.Constraints.Add(fkc);
            fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
            fkc.DeleteRule = System.Data.Rule.Cascade;
            fkc.UpdateRule = System.Data.Rule.Cascade;
            this.relationtblApplicationGrouptblMethodOfPaymentMap = new DataRelation("tblApplicationGrouptblMethodOfPaymentMap", new DataColumn[] {
                        this.tabletblApplicationGroup.grpIdColumn}, new DataColumn[] {
                        this.tableMethodsOfPayment.ApplicationGroupIdColumn}, false);
            this.Relations.Add(this.relationtblApplicationGrouptblMethodOfPaymentMap);
            this.relationtblPaymentTypetblMethodOfPaymentMap = new DataRelation("tblPaymentTypetblMethodOfPaymentMap", new DataColumn[] {
                        this.tabletblPaymentType.paytpIDColumn}, new DataColumn[] {
                        this.tableMethodsOfPayment.PaymentTypeIdColumn}, false);
            this.Relations.Add(this.relationtblPaymentTypetblMethodOfPaymentMap);
        }
        
        private bool ShouldSerializeMethodsOfPayment() {
            return false;
        }
        
        private bool ShouldSerializetblApplicationGroup() {
            return false;
        }
        
        private bool ShouldSerializetblPaymentType() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void MethodOfPaymentChangeEventHandler(object sender, MethodOfPaymentChangeEvent e);
        
        public delegate void tblApplicationGroupRowChangeEventHandler(object sender, tblApplicationGroupRowChangeEvent e);
        
        public delegate void tblPaymentTypeRowChangeEventHandler(object sender, tblPaymentTypeRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MethodsOfPaymentDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnId;
            
            private DataColumn columnPaymentTypeId;
            
            private DataColumn columnApplicationGroupId;
            
            private DataColumn columnMop;
            
            private DataColumn columnDescription;
            
            internal MethodsOfPaymentDataTable() : 
                    base("tblMethodOfPaymentMap") {
                this.InitClass();
            }
            
            internal MethodsOfPaymentDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IdColumn {
                get {
                    return this.columnId;
                }
            }
            
            internal DataColumn PaymentTypeIdColumn {
                get {
                    return this.columnPaymentTypeId;
                }
            }
            
            internal DataColumn ApplicationGroupIdColumn {
                get {
                    return this.columnApplicationGroupId;
                }
            }
            
            internal DataColumn MopColumn {
                get {
                    return this.columnMop;
                }
            }
            
            internal DataColumn DescriptionColumn {
                get {
                    return this.columnDescription;
                }
            }
            
            public MethodOfPayment this[int index] {
                get {
                    return ((MethodOfPayment)(this.Rows[index]));
                }
            }
            
            public event MethodOfPaymentChangeEventHandler MethodOfPaymentChanged;
            
            public event MethodOfPaymentChangeEventHandler MethodOfPaymentChanging;
            
            public event MethodOfPaymentChangeEventHandler MethodOfPaymentDeleted;
            
            public event MethodOfPaymentChangeEventHandler MethodOfPaymentDeleting;
            
            public void AddMethodOfPayment(MethodOfPayment row) {
                this.Rows.Add(row);
            }
            
            public MethodOfPayment AddMethodOfPayment(int Id, tblPaymentTypeRow parenttblPaymentTypeRowBytblPaymentTypetblMethodOfPaymentMap, tblApplicationGroupRow parenttblApplicationGroupRowBytblApplicationGrouptblMethodOfPaymentMap, int Mop, string Description) {
                MethodOfPayment rowMethodOfPayment = ((MethodOfPayment)(this.NewRow()));
                rowMethodOfPayment.ItemArray = new object[] {
                        Id,
                        parenttblPaymentTypeRowBytblPaymentTypetblMethodOfPaymentMap[0],
                        parenttblApplicationGroupRowBytblApplicationGrouptblMethodOfPaymentMap[0],
                        Mop,
                        Description};
                this.Rows.Add(rowMethodOfPayment);
                return rowMethodOfPayment;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                MethodsOfPaymentDataTable cln = ((MethodsOfPaymentDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new MethodsOfPaymentDataTable();
            }
            
            internal void InitVars() {
                this.columnId = this.Columns["mopId"];
                this.columnPaymentTypeId = this.Columns["mopPaymentTypeId"];
                this.columnApplicationGroupId = this.Columns["mopApplicationGroupId"];
                this.columnMop = this.Columns["mopMop"];
                this.columnDescription = this.Columns["mopDescription"];
            }
            
            private void InitClass() {
                this.columnId = new DataColumn("mopId", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnId);
                this.columnPaymentTypeId = new DataColumn("mopPaymentTypeId", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPaymentTypeId);
                this.columnApplicationGroupId = new DataColumn("mopApplicationGroupId", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnApplicationGroupId);
                this.columnMop = new DataColumn("mopMop", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnMop);
                this.columnDescription = new DataColumn("mopDescription", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDescription);
                this.Constraints.Add(new UniqueConstraint("MethodOfPaymentSchemaKey1", new DataColumn[] {
                                this.columnPaymentTypeId,
                                this.columnApplicationGroupId}, false));
                this.columnId.AllowDBNull = false;
            }
            
            public MethodOfPayment NewMethodOfPayment() {
                return ((MethodOfPayment)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new MethodOfPayment(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(MethodOfPayment);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MethodOfPaymentChanged != null)) {
                    this.MethodOfPaymentChanged(this, new MethodOfPaymentChangeEvent(((MethodOfPayment)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MethodOfPaymentChanging != null)) {
                    this.MethodOfPaymentChanging(this, new MethodOfPaymentChangeEvent(((MethodOfPayment)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MethodOfPaymentDeleted != null)) {
                    this.MethodOfPaymentDeleted(this, new MethodOfPaymentChangeEvent(((MethodOfPayment)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MethodOfPaymentDeleting != null)) {
                    this.MethodOfPaymentDeleting(this, new MethodOfPaymentChangeEvent(((MethodOfPayment)(e.Row)), e.Action));
                }
            }
            
            public void RemoveMethodOfPayment(MethodOfPayment row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MethodOfPayment : DataRow {
            
            private MethodsOfPaymentDataTable tableMethodsOfPayment;
            
            internal MethodOfPayment(DataRowBuilder rb) : 
                    base(rb) {
                this.tableMethodsOfPayment = ((MethodsOfPaymentDataTable)(this.Table));
            }
            
            public int Id {
                get {
                    return ((int)(this[this.tableMethodsOfPayment.IdColumn]));
                }
                set {
                    this[this.tableMethodsOfPayment.IdColumn] = value;
                }
            }
            
            public int PaymentTypeId {
                get {
                    try {
                        return ((int)(this[this.tableMethodsOfPayment.PaymentTypeIdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMethodsOfPayment.PaymentTypeIdColumn] = value;
                }
            }
            
            public int ApplicationGroupId {
                get {
                    try {
                        return ((int)(this[this.tableMethodsOfPayment.ApplicationGroupIdColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMethodsOfPayment.ApplicationGroupIdColumn] = value;
                }
            }
            
            public int Mop {
                get {
                    try {
                        return ((int)(this[this.tableMethodsOfPayment.MopColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMethodsOfPayment.MopColumn] = value;
                }
            }
            
            public string Description {
                get {
                    try {
                        return ((string)(this[this.tableMethodsOfPayment.DescriptionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableMethodsOfPayment.DescriptionColumn] = value;
                }
            }
            
            public tblApplicationGroupRow tblApplicationGroupRow {
                get {
                    return ((tblApplicationGroupRow)(this.GetParentRow(this.Table.ParentRelations["tblApplicationGrouptblMethodOfPaymentMap"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["tblApplicationGrouptblMethodOfPaymentMap"]);
                }
            }
            
            public tblPaymentTypeRow tblPaymentTypeRow {
                get {
                    return ((tblPaymentTypeRow)(this.GetParentRow(this.Table.ParentRelations["tblPaymentTypetblMethodOfPaymentMap"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["tblPaymentTypetblMethodOfPaymentMap"]);
                }
            }
            
            public bool IsPaymentTypeIdNull() {
                return this.IsNull(this.tableMethodsOfPayment.PaymentTypeIdColumn);
            }
            
            public void SetPaymentTypeIdNull() {
                this[this.tableMethodsOfPayment.PaymentTypeIdColumn] = System.Convert.DBNull;
            }
            
            public bool IsApplicationGroupIdNull() {
                return this.IsNull(this.tableMethodsOfPayment.ApplicationGroupIdColumn);
            }
            
            public void SetApplicationGroupIdNull() {
                this[this.tableMethodsOfPayment.ApplicationGroupIdColumn] = System.Convert.DBNull;
            }
            
            public bool IsMopNull() {
                return this.IsNull(this.tableMethodsOfPayment.MopColumn);
            }
            
            public void SetMopNull() {
                this[this.tableMethodsOfPayment.MopColumn] = System.Convert.DBNull;
            }
            
            public bool IsDescriptionNull() {
                return this.IsNull(this.tableMethodsOfPayment.DescriptionColumn);
            }
            
            public void SetDescriptionNull() {
                this[this.tableMethodsOfPayment.DescriptionColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class MethodOfPaymentChangeEvent : EventArgs {
            
            private MethodOfPayment eventRow;
            
            private DataRowAction eventAction;
            
            public MethodOfPaymentChangeEvent(MethodOfPayment row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public MethodOfPayment Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblApplicationGroupDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columngrpId;
            
            private DataColumn columngrpName;
            
            private DataColumn columngrpCredentialId;
            
            internal tblApplicationGroupDataTable() : 
                    base("tblApplicationGroup") {
                this.InitClass();
            }
            
            internal tblApplicationGroupDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn grpIdColumn {
                get {
                    return this.columngrpId;
                }
            }
            
            internal DataColumn grpNameColumn {
                get {
                    return this.columngrpName;
                }
            }
            
            internal DataColumn grpCredentialIdColumn {
                get {
                    return this.columngrpCredentialId;
                }
            }
            
            public tblApplicationGroupRow this[int index] {
                get {
                    return ((tblApplicationGroupRow)(this.Rows[index]));
                }
            }
            
            public event tblApplicationGroupRowChangeEventHandler tblApplicationGroupRowChanged;
            
            public event tblApplicationGroupRowChangeEventHandler tblApplicationGroupRowChanging;
            
            public event tblApplicationGroupRowChangeEventHandler tblApplicationGroupRowDeleted;
            
            public event tblApplicationGroupRowChangeEventHandler tblApplicationGroupRowDeleting;
            
            public void AddtblApplicationGroupRow(tblApplicationGroupRow row) {
                this.Rows.Add(row);
            }
            
            public tblApplicationGroupRow AddtblApplicationGroupRow(string grpName, int grpCredentialId) {
                tblApplicationGroupRow rowtblApplicationGroupRow = ((tblApplicationGroupRow)(this.NewRow()));
                rowtblApplicationGroupRow.ItemArray = new object[] {
                        null,
                        grpName,
                        grpCredentialId};
                this.Rows.Add(rowtblApplicationGroupRow);
                return rowtblApplicationGroupRow;
            }
            
            public tblApplicationGroupRow FindBygrpId(int grpId) {
                return ((tblApplicationGroupRow)(this.Rows.Find(new object[] {
                            grpId})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tblApplicationGroupDataTable cln = ((tblApplicationGroupDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tblApplicationGroupDataTable();
            }
            
            internal void InitVars() {
                this.columngrpId = this.Columns["grpId"];
                this.columngrpName = this.Columns["grpName"];
                this.columngrpCredentialId = this.Columns["grpCredentialId"];
            }
            
            private void InitClass() {
                this.columngrpId = new DataColumn("grpId", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngrpId);
                this.columngrpName = new DataColumn("grpName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngrpName);
                this.columngrpCredentialId = new DataColumn("grpCredentialId", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columngrpCredentialId);
                this.Constraints.Add(new UniqueConstraint("MethodOfPaymentSchemaKey2", new DataColumn[] {
                                this.columngrpId}, true));
                this.columngrpId.AutoIncrement = true;
                this.columngrpId.AllowDBNull = false;
                this.columngrpId.ReadOnly = true;
                this.columngrpId.Unique = true;
                this.columngrpName.AllowDBNull = false;
                this.columngrpCredentialId.AllowDBNull = false;
            }
            
            public tblApplicationGroupRow NewtblApplicationGroupRow() {
                return ((tblApplicationGroupRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tblApplicationGroupRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tblApplicationGroupRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblApplicationGroupRowChanged != null)) {
                    this.tblApplicationGroupRowChanged(this, new tblApplicationGroupRowChangeEvent(((tblApplicationGroupRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblApplicationGroupRowChanging != null)) {
                    this.tblApplicationGroupRowChanging(this, new tblApplicationGroupRowChangeEvent(((tblApplicationGroupRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblApplicationGroupRowDeleted != null)) {
                    this.tblApplicationGroupRowDeleted(this, new tblApplicationGroupRowChangeEvent(((tblApplicationGroupRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblApplicationGroupRowDeleting != null)) {
                    this.tblApplicationGroupRowDeleting(this, new tblApplicationGroupRowChangeEvent(((tblApplicationGroupRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetblApplicationGroupRow(tblApplicationGroupRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblApplicationGroupRow : DataRow {
            
            private tblApplicationGroupDataTable tabletblApplicationGroup;
            
            internal tblApplicationGroupRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblApplicationGroup = ((tblApplicationGroupDataTable)(this.Table));
            }
            
            public int grpId {
                get {
                    return ((int)(this[this.tabletblApplicationGroup.grpIdColumn]));
                }
                set {
                    this[this.tabletblApplicationGroup.grpIdColumn] = value;
                }
            }
            
            public string grpName {
                get {
                    return ((string)(this[this.tabletblApplicationGroup.grpNameColumn]));
                }
                set {
                    this[this.tabletblApplicationGroup.grpNameColumn] = value;
                }
            }
            
            public int grpCredentialId {
                get {
                    return ((int)(this[this.tabletblApplicationGroup.grpCredentialIdColumn]));
                }
                set {
                    this[this.tabletblApplicationGroup.grpCredentialIdColumn] = value;
                }
            }
            
            public MethodOfPayment[] GetMethodsOfPayment() {
                return ((MethodOfPayment[])(this.GetChildRows(this.Table.ChildRelations["tblApplicationGrouptblMethodOfPaymentMap"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblApplicationGroupRowChangeEvent : EventArgs {
            
            private tblApplicationGroupRow eventRow;
            
            private DataRowAction eventAction;
            
            public tblApplicationGroupRowChangeEvent(tblApplicationGroupRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tblApplicationGroupRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblPaymentTypeDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnpaytpID;
            
            private DataColumn columnpaytpName;
            
            private DataColumn columnpaytpDescription;
            
            internal tblPaymentTypeDataTable() : 
                    base("tblPaymentType") {
                this.InitClass();
            }
            
            internal tblPaymentTypeDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn paytpIDColumn {
                get {
                    return this.columnpaytpID;
                }
            }
            
            internal DataColumn paytpNameColumn {
                get {
                    return this.columnpaytpName;
                }
            }
            
            internal DataColumn paytpDescriptionColumn {
                get {
                    return this.columnpaytpDescription;
                }
            }
            
            public tblPaymentTypeRow this[int index] {
                get {
                    return ((tblPaymentTypeRow)(this.Rows[index]));
                }
            }
            
            public event tblPaymentTypeRowChangeEventHandler tblPaymentTypeRowChanged;
            
            public event tblPaymentTypeRowChangeEventHandler tblPaymentTypeRowChanging;
            
            public event tblPaymentTypeRowChangeEventHandler tblPaymentTypeRowDeleted;
            
            public event tblPaymentTypeRowChangeEventHandler tblPaymentTypeRowDeleting;
            
            public void AddtblPaymentTypeRow(tblPaymentTypeRow row) {
                this.Rows.Add(row);
            }
            
            public tblPaymentTypeRow AddtblPaymentTypeRow(int paytpID, string paytpName, string paytpDescription) {
                tblPaymentTypeRow rowtblPaymentTypeRow = ((tblPaymentTypeRow)(this.NewRow()));
                rowtblPaymentTypeRow.ItemArray = new object[] {
                        paytpID,
                        paytpName,
                        paytpDescription};
                this.Rows.Add(rowtblPaymentTypeRow);
                return rowtblPaymentTypeRow;
            }
            
            public tblPaymentTypeRow FindBypaytpID(int paytpID) {
                return ((tblPaymentTypeRow)(this.Rows.Find(new object[] {
                            paytpID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tblPaymentTypeDataTable cln = ((tblPaymentTypeDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tblPaymentTypeDataTable();
            }
            
            internal void InitVars() {
                this.columnpaytpID = this.Columns["paytpID"];
                this.columnpaytpName = this.Columns["paytpName"];
                this.columnpaytpDescription = this.Columns["paytpDescription"];
            }
            
            private void InitClass() {
                this.columnpaytpID = new DataColumn("paytpID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpaytpID);
                this.columnpaytpName = new DataColumn("paytpName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpaytpName);
                this.columnpaytpDescription = new DataColumn("paytpDescription", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpaytpDescription);
                this.Constraints.Add(new UniqueConstraint("MethodOfPaymentSchemaKey3", new DataColumn[] {
                                this.columnpaytpID}, true));
                this.columnpaytpID.AllowDBNull = false;
                this.columnpaytpID.Unique = true;
                this.columnpaytpName.AllowDBNull = false;
            }
            
            public tblPaymentTypeRow NewtblPaymentTypeRow() {
                return ((tblPaymentTypeRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tblPaymentTypeRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tblPaymentTypeRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tblPaymentTypeRowChanged != null)) {
                    this.tblPaymentTypeRowChanged(this, new tblPaymentTypeRowChangeEvent(((tblPaymentTypeRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tblPaymentTypeRowChanging != null)) {
                    this.tblPaymentTypeRowChanging(this, new tblPaymentTypeRowChangeEvent(((tblPaymentTypeRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tblPaymentTypeRowDeleted != null)) {
                    this.tblPaymentTypeRowDeleted(this, new tblPaymentTypeRowChangeEvent(((tblPaymentTypeRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tblPaymentTypeRowDeleting != null)) {
                    this.tblPaymentTypeRowDeleting(this, new tblPaymentTypeRowChangeEvent(((tblPaymentTypeRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetblPaymentTypeRow(tblPaymentTypeRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblPaymentTypeRow : DataRow {
            
            private tblPaymentTypeDataTable tabletblPaymentType;
            
            internal tblPaymentTypeRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletblPaymentType = ((tblPaymentTypeDataTable)(this.Table));
            }
            
            public int paytpID {
                get {
                    return ((int)(this[this.tabletblPaymentType.paytpIDColumn]));
                }
                set {
                    this[this.tabletblPaymentType.paytpIDColumn] = value;
                }
            }
            
            public string paytpName {
                get {
                    return ((string)(this[this.tabletblPaymentType.paytpNameColumn]));
                }
                set {
                    this[this.tabletblPaymentType.paytpNameColumn] = value;
                }
            }
            
            public string paytpDescription {
                get {
                    try {
                        return ((string)(this[this.tabletblPaymentType.paytpDescriptionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletblPaymentType.paytpDescriptionColumn] = value;
                }
            }
            
            public bool IspaytpDescriptionNull() {
                return this.IsNull(this.tabletblPaymentType.paytpDescriptionColumn);
            }
            
            public void SetpaytpDescriptionNull() {
                this[this.tabletblPaymentType.paytpDescriptionColumn] = System.Convert.DBNull;
            }
            
            public MethodOfPayment[] GetMethodsOfPayment() {
                return ((MethodOfPayment[])(this.GetChildRows(this.Table.ChildRelations["tblPaymentTypetblMethodOfPaymentMap"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tblPaymentTypeRowChangeEvent : EventArgs {
            
            private tblPaymentTypeRow eventRow;
            
            private DataRowAction eventAction;
            
            public tblPaymentTypeRowChangeEvent(tblPaymentTypeRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tblPaymentTypeRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
