//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Cox.DataAccess.Enterprise {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("SiteCodeSchema")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class SiteCodeSchema : System.Data.DataSet {
        
        private CompanyDivisionSitesDataTable tableCompanyDivisionSites;
        
        private CoxSitesDataTable tableCoxSites;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SiteCodeSchema() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected SiteCodeSchema(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tblCompanyDivision"] != null)) {
                    base.Tables.Add(new CompanyDivisionSitesDataTable(ds.Tables["tblCompanyDivision"]));
                }
                if ((ds.Tables["tblSite"] != null)) {
                    base.Tables.Add(new CoxSitesDataTable(ds.Tables["tblSite"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CompanyDivisionSitesDataTable CompanyDivisionSites {
            get {
                return this.tableCompanyDivisionSites;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CoxSitesDataTable CoxSites {
            get {
                return this.tableCoxSites;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            SiteCodeSchema cln = ((SiteCodeSchema)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tblCompanyDivision"] != null)) {
                    base.Tables.Add(new CompanyDivisionSitesDataTable(ds.Tables["tblCompanyDivision"]));
                }
                if ((ds.Tables["tblSite"] != null)) {
                    base.Tables.Add(new CoxSitesDataTable(ds.Tables["tblSite"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableCompanyDivisionSites = ((CompanyDivisionSitesDataTable)(base.Tables["tblCompanyDivision"]));
            if ((initTable == true)) {
                if ((this.tableCompanyDivisionSites != null)) {
                    this.tableCompanyDivisionSites.InitVars();
                }
            }
            this.tableCoxSites = ((CoxSitesDataTable)(base.Tables["tblSite"]));
            if ((initTable == true)) {
                if ((this.tableCoxSites != null)) {
                    this.tableCoxSites.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "SiteCodeSchema";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/SiteCodeSchema.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableCompanyDivisionSites = new CompanyDivisionSitesDataTable();
            base.Tables.Add(this.tableCompanyDivisionSites);
            this.tableCoxSites = new CoxSitesDataTable();
            base.Tables.Add(this.tableCoxSites);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeCompanyDivisionSites() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeCoxSites() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            SiteCodeSchema ds = new SiteCodeSchema();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void CompanyDivisionSiteChangeEventHandler(object sender, CompanyDivisionSiteChangeEvent e);
        
        public delegate void CoxSiteChangeEventHandler(object sender, CoxSiteChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CompanyDivisionSitesDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnSiteId;
            
            private System.Data.DataColumn columnCompanyNumber;
            
            private System.Data.DataColumn columnDivisionNumber;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CompanyDivisionSitesDataTable() {
                this.TableName = "tblCompanyDivision";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CompanyDivisionSitesDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected CompanyDivisionSitesDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SiteIdColumn {
                get {
                    return this.columnSiteId;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn CompanyNumberColumn {
                get {
                    return this.columnCompanyNumber;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn DivisionNumberColumn {
                get {
                    return this.columnDivisionNumber;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CompanyDivisionSite this[int index] {
                get {
                    return ((CompanyDivisionSite)(this.Rows[index]));
                }
            }
            
            public event CompanyDivisionSiteChangeEventHandler CompanyDivisionSiteChanging;
            
            public event CompanyDivisionSiteChangeEventHandler CompanyDivisionSiteChanged;
            
            public event CompanyDivisionSiteChangeEventHandler CompanyDivisionSiteDeleting;
            
            public event CompanyDivisionSiteChangeEventHandler CompanyDivisionSiteDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddCompanyDivisionSite(CompanyDivisionSite row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CompanyDivisionSite AddCompanyDivisionSite(int SiteId, int CompanyNumber, int DivisionNumber) {
                CompanyDivisionSite rowCompanyDivisionSite = ((CompanyDivisionSite)(this.NewRow()));
                rowCompanyDivisionSite.ItemArray = new object[] {
                        SiteId,
                        CompanyNumber,
                        DivisionNumber};
                this.Rows.Add(rowCompanyDivisionSite);
                return rowCompanyDivisionSite;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CompanyDivisionSite FindBySiteIdCompanyNumberDivisionNumber(int SiteId, int CompanyNumber, int DivisionNumber) {
                return ((CompanyDivisionSite)(this.Rows.Find(new object[] {
                            SiteId,
                            CompanyNumber,
                            DivisionNumber})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                CompanyDivisionSitesDataTable cln = ((CompanyDivisionSitesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new CompanyDivisionSitesDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnSiteId = base.Columns["cpdvSiteId"];
                this.columnCompanyNumber = base.Columns["cpdvCompanyNumber"];
                this.columnDivisionNumber = base.Columns["cpdvDivisionNumber"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnSiteId = new System.Data.DataColumn("cpdvSiteId", typeof(int), null, System.Data.MappingType.Element);
                this.columnSiteId.ExtendedProperties.Add("typedName", "SiteId");
                base.Columns.Add(this.columnSiteId);
                this.columnCompanyNumber = new System.Data.DataColumn("cpdvCompanyNumber", typeof(int), null, System.Data.MappingType.Element);
                this.columnCompanyNumber.ExtendedProperties.Add("typedName", "CompanyNumber");
                base.Columns.Add(this.columnCompanyNumber);
                this.columnDivisionNumber = new System.Data.DataColumn("cpdvDivisionNumber", typeof(int), null, System.Data.MappingType.Element);
                this.columnDivisionNumber.ExtendedProperties.Add("typedName", "DivisionNumber");
                base.Columns.Add(this.columnDivisionNumber);
                this.Constraints.Add(new System.Data.UniqueConstraint("tblCompanyDivisionKey1", new System.Data.DataColumn[] {
                                this.columnSiteId,
                                this.columnCompanyNumber,
                                this.columnDivisionNumber}, true));
                this.columnSiteId.AllowDBNull = false;
                this.columnCompanyNumber.AllowDBNull = false;
                this.columnDivisionNumber.AllowDBNull = false;
                this.ExtendedProperties.Add("typedName", "CompanyDivisionSite");
                this.ExtendedProperties.Add("typedPlural", "CompanyDivisionSites");
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CompanyDivisionSite NewCompanyDivisionSite() {
                return ((CompanyDivisionSite)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new CompanyDivisionSite(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(CompanyDivisionSite);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CompanyDivisionSiteChanged != null)) {
                    this.CompanyDivisionSiteChanged(this, new CompanyDivisionSiteChangeEvent(((CompanyDivisionSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CompanyDivisionSiteChanging != null)) {
                    this.CompanyDivisionSiteChanging(this, new CompanyDivisionSiteChangeEvent(((CompanyDivisionSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CompanyDivisionSiteDeleted != null)) {
                    this.CompanyDivisionSiteDeleted(this, new CompanyDivisionSiteChangeEvent(((CompanyDivisionSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CompanyDivisionSiteDeleting != null)) {
                    this.CompanyDivisionSiteDeleting(this, new CompanyDivisionSiteChangeEvent(((CompanyDivisionSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveCompanyDivisionSite(CompanyDivisionSite row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                SiteCodeSchema ds = new SiteCodeSchema();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CompanyDivisionSitesDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CoxSitesDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnSiteId;
            
            private System.Data.DataColumn columnSiteCode;
            
            private System.Data.DataColumn columnSiteDescription;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CoxSitesDataTable() {
                this.TableName = "tblSite";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CoxSitesDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected CoxSitesDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SiteIdColumn {
                get {
                    return this.columnSiteId;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SiteCodeColumn {
                get {
                    return this.columnSiteCode;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SiteDescriptionColumn {
                get {
                    return this.columnSiteDescription;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CoxSite this[int index] {
                get {
                    return ((CoxSite)(this.Rows[index]));
                }
            }
            
            public event CoxSiteChangeEventHandler CoxSiteChanging;
            
            public event CoxSiteChangeEventHandler CoxSiteChanged;
            
            public event CoxSiteChangeEventHandler CoxSiteDeleting;
            
            public event CoxSiteChangeEventHandler CoxSiteDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddCoxSite(CoxSite row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CoxSite AddCoxSite(int SiteId, string SiteCode, string SiteDescription) {
                CoxSite rowCoxSite = ((CoxSite)(this.NewRow()));
                rowCoxSite.ItemArray = new object[] {
                        SiteId,
                        SiteCode,
                        SiteDescription};
                this.Rows.Add(rowCoxSite);
                return rowCoxSite;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CoxSite FindBySiteId(int SiteId) {
                return ((CoxSite)(this.Rows.Find(new object[] {
                            SiteId})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                CoxSitesDataTable cln = ((CoxSitesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new CoxSitesDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnSiteId = base.Columns["stId"];
                this.columnSiteCode = base.Columns["stCode"];
                this.columnSiteDescription = base.Columns["stDescription"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnSiteId = new System.Data.DataColumn("stId", typeof(int), null, System.Data.MappingType.Element);
                this.columnSiteId.ExtendedProperties.Add("typedName", "SiteId");
                base.Columns.Add(this.columnSiteId);
                this.columnSiteCode = new System.Data.DataColumn("stCode", typeof(string), null, System.Data.MappingType.Element);
                this.columnSiteCode.ExtendedProperties.Add("typedName", "SiteCode");
                base.Columns.Add(this.columnSiteCode);
                this.columnSiteDescription = new System.Data.DataColumn("stDescription", typeof(string), null, System.Data.MappingType.Element);
                this.columnSiteDescription.ExtendedProperties.Add("typedName", "SiteDescription");
                base.Columns.Add(this.columnSiteDescription);
                this.Constraints.Add(new System.Data.UniqueConstraint("tblSiteKey1", new System.Data.DataColumn[] {
                                this.columnSiteId}, true));
                this.columnSiteId.AllowDBNull = false;
                this.columnSiteId.Unique = true;
                this.columnSiteCode.AllowDBNull = false;
                this.ExtendedProperties.Add("typedName", "CoxSite");
                this.ExtendedProperties.Add("typedPlural", "CoxSites");
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CoxSite NewCoxSite() {
                return ((CoxSite)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new CoxSite(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(CoxSite);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CoxSiteChanged != null)) {
                    this.CoxSiteChanged(this, new CoxSiteChangeEvent(((CoxSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CoxSiteChanging != null)) {
                    this.CoxSiteChanging(this, new CoxSiteChangeEvent(((CoxSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CoxSiteDeleted != null)) {
                    this.CoxSiteDeleted(this, new CoxSiteChangeEvent(((CoxSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CoxSiteDeleting != null)) {
                    this.CoxSiteDeleting(this, new CoxSiteChangeEvent(((CoxSite)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveCoxSite(CoxSite row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                SiteCodeSchema ds = new SiteCodeSchema();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CoxSitesDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class CompanyDivisionSite : System.Data.DataRow {
            
            private CompanyDivisionSitesDataTable tableCompanyDivisionSites;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CompanyDivisionSite(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCompanyDivisionSites = ((CompanyDivisionSitesDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int SiteId {
                get {
                    return ((int)(this[this.tableCompanyDivisionSites.SiteIdColumn]));
                }
                set {
                    this[this.tableCompanyDivisionSites.SiteIdColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int CompanyNumber {
                get {
                    return ((int)(this[this.tableCompanyDivisionSites.CompanyNumberColumn]));
                }
                set {
                    this[this.tableCompanyDivisionSites.CompanyNumberColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int DivisionNumber {
                get {
                    return ((int)(this[this.tableCompanyDivisionSites.DivisionNumberColumn]));
                }
                set {
                    this[this.tableCompanyDivisionSites.DivisionNumberColumn] = value;
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class CoxSite : System.Data.DataRow {
            
            private CoxSitesDataTable tableCoxSites;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal CoxSite(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCoxSites = ((CoxSitesDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int SiteId {
                get {
                    return ((int)(this[this.tableCoxSites.SiteIdColumn]));
                }
                set {
                    this[this.tableCoxSites.SiteIdColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SiteCode {
                get {
                    return ((string)(this[this.tableCoxSites.SiteCodeColumn]));
                }
                set {
                    this[this.tableCoxSites.SiteCodeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SiteDescription {
                get {
                    try {
                        return ((string)(this[this.tableCoxSites.SiteDescriptionColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'stDescription\' in table \'tblSite\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableCoxSites.SiteDescriptionColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSiteDescriptionNull() {
                return this.IsNull(this.tableCoxSites.SiteDescriptionColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSiteDescriptionNull() {
                this[this.tableCoxSites.SiteDescriptionColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class CompanyDivisionSiteChangeEvent : System.EventArgs {
            
            private CompanyDivisionSite eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CompanyDivisionSiteChangeEvent(CompanyDivisionSite row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CompanyDivisionSite Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class CoxSiteChangeEvent : System.EventArgs {
            
            private CoxSite eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CoxSiteChangeEvent(CoxSite row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public CoxSite Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591