//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Cox.DataAccess.Account {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("InstallationSchema")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class InstallationSchema : System.Data.DataSet {
        
        private InstallationSlotsDataTable tableInstallationSlots;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public InstallationSchema() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected InstallationSchema(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["InstallationSlots"] != null)) {
                    base.Tables.Add(new InstallationSlotsDataTable(ds.Tables["InstallationSlots"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public InstallationSlotsDataTable InstallationSlots {
            get {
                return this.tableInstallationSlots;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            InstallationSchema cln = ((InstallationSchema)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["InstallationSlots"] != null)) {
                    base.Tables.Add(new InstallationSlotsDataTable(ds.Tables["InstallationSlots"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableInstallationSlots = ((InstallationSlotsDataTable)(base.Tables["InstallationSlots"]));
            if ((initTable == true)) {
                if ((this.tableInstallationSlots != null)) {
                    this.tableInstallationSlots.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "InstallationSchema";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/InstallationSchema.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableInstallationSlots = new InstallationSlotsDataTable();
            base.Tables.Add(this.tableInstallationSlots);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeInstallationSlots() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            InstallationSchema ds = new InstallationSchema();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void InstallationSlotsRowChangeEventHandler(object sender, InstallationSlotsRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class InstallationSlotsDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnSITE_ID;
            
            private System.Data.DataColumn columnTIME_SLOT;
            
            private System.Data.DataColumn columnSCHEDULE_DATE;
            
            private System.Data.DataColumn columnSUN_START_TIME;
            
            private System.Data.DataColumn columnSUN_END_TIME;
            
            private System.Data.DataColumn columnMON_START_TIME;
            
            private System.Data.DataColumn columnMON_END_TIME;
            
            private System.Data.DataColumn columnTUE_START_TIME;
            
            private System.Data.DataColumn columnTUE_END_TIME;
            
            private System.Data.DataColumn columnWED_START_TIME;
            
            private System.Data.DataColumn columnWED_END_TIME;
            
            private System.Data.DataColumn columnTHU_START_TIME;
            
            private System.Data.DataColumn columnTHU_END_TIME;
            
            private System.Data.DataColumn columnFRI_START_TIME;
            
            private System.Data.DataColumn columnFRI_END_TIME;
            
            private System.Data.DataColumn columnSAT_START_TIME;
            
            private System.Data.DataColumn columnSAT_END_TIME;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InstallationSlotsDataTable() {
                this.TableName = "InstallationSlots";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal InstallationSlotsDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected InstallationSlotsDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SITE_IDColumn {
                get {
                    return this.columnSITE_ID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TIME_SLOTColumn {
                get {
                    return this.columnTIME_SLOT;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SCHEDULE_DATEColumn {
                get {
                    return this.columnSCHEDULE_DATE;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SUN_START_TIMEColumn {
                get {
                    return this.columnSUN_START_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SUN_END_TIMEColumn {
                get {
                    return this.columnSUN_END_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn MON_START_TIMEColumn {
                get {
                    return this.columnMON_START_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn MON_END_TIMEColumn {
                get {
                    return this.columnMON_END_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TUE_START_TIMEColumn {
                get {
                    return this.columnTUE_START_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn TUE_END_TIMEColumn {
                get {
                    return this.columnTUE_END_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn WED_START_TIMEColumn {
                get {
                    return this.columnWED_START_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn WED_END_TIMEColumn {
                get {
                    return this.columnWED_END_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn THU_START_TIMEColumn {
                get {
                    return this.columnTHU_START_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn THU_END_TIMEColumn {
                get {
                    return this.columnTHU_END_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn FRI_START_TIMEColumn {
                get {
                    return this.columnFRI_START_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn FRI_END_TIMEColumn {
                get {
                    return this.columnFRI_END_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SAT_START_TIMEColumn {
                get {
                    return this.columnSAT_START_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn SAT_END_TIMEColumn {
                get {
                    return this.columnSAT_END_TIME;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InstallationSlotsRow this[int index] {
                get {
                    return ((InstallationSlotsRow)(this.Rows[index]));
                }
            }
            
            public event InstallationSlotsRowChangeEventHandler InstallationSlotsRowChanging;
            
            public event InstallationSlotsRowChangeEventHandler InstallationSlotsRowChanged;
            
            public event InstallationSlotsRowChangeEventHandler InstallationSlotsRowDeleting;
            
            public event InstallationSlotsRowChangeEventHandler InstallationSlotsRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddInstallationSlotsRow(InstallationSlotsRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InstallationSlotsRow AddInstallationSlotsRow(
                        long SITE_ID, 
                        string TIME_SLOT, 
                        System.DateTime SCHEDULE_DATE, 
                        decimal SUN_START_TIME, 
                        decimal SUN_END_TIME, 
                        decimal MON_START_TIME, 
                        decimal MON_END_TIME, 
                        decimal TUE_START_TIME, 
                        decimal TUE_END_TIME, 
                        decimal WED_START_TIME, 
                        decimal WED_END_TIME, 
                        decimal THU_START_TIME, 
                        decimal THU_END_TIME, 
                        decimal FRI_START_TIME, 
                        decimal FRI_END_TIME, 
                        decimal SAT_START_TIME, 
                        decimal SAT_END_TIME) {
                InstallationSlotsRow rowInstallationSlotsRow = ((InstallationSlotsRow)(this.NewRow()));
                rowInstallationSlotsRow.ItemArray = new object[] {
                        SITE_ID,
                        TIME_SLOT,
                        SCHEDULE_DATE,
                        SUN_START_TIME,
                        SUN_END_TIME,
                        MON_START_TIME,
                        MON_END_TIME,
                        TUE_START_TIME,
                        TUE_END_TIME,
                        WED_START_TIME,
                        WED_END_TIME,
                        THU_START_TIME,
                        THU_END_TIME,
                        FRI_START_TIME,
                        FRI_END_TIME,
                        SAT_START_TIME,
                        SAT_END_TIME};
                this.Rows.Add(rowInstallationSlotsRow);
                return rowInstallationSlotsRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                InstallationSlotsDataTable cln = ((InstallationSlotsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new InstallationSlotsDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnSITE_ID = base.Columns["SITE_ID"];
                this.columnTIME_SLOT = base.Columns["TIME_SLOT"];
                this.columnSCHEDULE_DATE = base.Columns["SCHEDULE_DATE"];
                this.columnSUN_START_TIME = base.Columns["SUN_START_TIME"];
                this.columnSUN_END_TIME = base.Columns["SUN_END_TIME"];
                this.columnMON_START_TIME = base.Columns["MON_START_TIME"];
                this.columnMON_END_TIME = base.Columns["MON_END_TIME"];
                this.columnTUE_START_TIME = base.Columns["TUE_START_TIME"];
                this.columnTUE_END_TIME = base.Columns["TUE_END_TIME"];
                this.columnWED_START_TIME = base.Columns["WED_START_TIME"];
                this.columnWED_END_TIME = base.Columns["WED_END_TIME"];
                this.columnTHU_START_TIME = base.Columns["THU_START_TIME"];
                this.columnTHU_END_TIME = base.Columns["THU_END_TIME"];
                this.columnFRI_START_TIME = base.Columns["FRI_START_TIME"];
                this.columnFRI_END_TIME = base.Columns["FRI_END_TIME"];
                this.columnSAT_START_TIME = base.Columns["SAT_START_TIME"];
                this.columnSAT_END_TIME = base.Columns["SAT_END_TIME"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnSITE_ID = new System.Data.DataColumn("SITE_ID", typeof(long), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSITE_ID);
                this.columnTIME_SLOT = new System.Data.DataColumn("TIME_SLOT", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTIME_SLOT);
                this.columnSCHEDULE_DATE = new System.Data.DataColumn("SCHEDULE_DATE", typeof(System.DateTime), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSCHEDULE_DATE);
                this.columnSUN_START_TIME = new System.Data.DataColumn("SUN_START_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUN_START_TIME);
                this.columnSUN_END_TIME = new System.Data.DataColumn("SUN_END_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSUN_END_TIME);
                this.columnMON_START_TIME = new System.Data.DataColumn("MON_START_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnMON_START_TIME);
                this.columnMON_END_TIME = new System.Data.DataColumn("MON_END_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnMON_END_TIME);
                this.columnTUE_START_TIME = new System.Data.DataColumn("TUE_START_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTUE_START_TIME);
                this.columnTUE_END_TIME = new System.Data.DataColumn("TUE_END_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTUE_END_TIME);
                this.columnWED_START_TIME = new System.Data.DataColumn("WED_START_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnWED_START_TIME);
                this.columnWED_END_TIME = new System.Data.DataColumn("WED_END_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnWED_END_TIME);
                this.columnTHU_START_TIME = new System.Data.DataColumn("THU_START_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHU_START_TIME);
                this.columnTHU_END_TIME = new System.Data.DataColumn("THU_END_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnTHU_END_TIME);
                this.columnFRI_START_TIME = new System.Data.DataColumn("FRI_START_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnFRI_START_TIME);
                this.columnFRI_END_TIME = new System.Data.DataColumn("FRI_END_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnFRI_END_TIME);
                this.columnSAT_START_TIME = new System.Data.DataColumn("SAT_START_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSAT_START_TIME);
                this.columnSAT_END_TIME = new System.Data.DataColumn("SAT_END_TIME", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnSAT_END_TIME);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InstallationSlotsRow NewInstallationSlotsRow() {
                return ((InstallationSlotsRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new InstallationSlotsRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(InstallationSlotsRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.InstallationSlotsRowChanged != null)) {
                    this.InstallationSlotsRowChanged(this, new InstallationSlotsRowChangeEvent(((InstallationSlotsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.InstallationSlotsRowChanging != null)) {
                    this.InstallationSlotsRowChanging(this, new InstallationSlotsRowChangeEvent(((InstallationSlotsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.InstallationSlotsRowDeleted != null)) {
                    this.InstallationSlotsRowDeleted(this, new InstallationSlotsRowChangeEvent(((InstallationSlotsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.InstallationSlotsRowDeleting != null)) {
                    this.InstallationSlotsRowDeleting(this, new InstallationSlotsRowChangeEvent(((InstallationSlotsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveInstallationSlotsRow(InstallationSlotsRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                InstallationSchema ds = new InstallationSchema();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "InstallationSlotsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class InstallationSlotsRow : System.Data.DataRow {
            
            private InstallationSlotsDataTable tableInstallationSlots;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal InstallationSlotsRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableInstallationSlots = ((InstallationSlotsDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public long SITE_ID {
                get {
                    try {
                        return ((long)(this[this.tableInstallationSlots.SITE_IDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'SITE_ID\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.SITE_IDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TIME_SLOT {
                get {
                    try {
                        return ((string)(this[this.tableInstallationSlots.TIME_SLOTColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'TIME_SLOT\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.TIME_SLOTColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime SCHEDULE_DATE {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableInstallationSlots.SCHEDULE_DATEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'SCHEDULE_DATE\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.SCHEDULE_DATEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SUN_START_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.SUN_START_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'SUN_START_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.SUN_START_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SUN_END_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.SUN_END_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'SUN_END_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.SUN_END_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal MON_START_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.MON_START_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'MON_START_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.MON_START_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal MON_END_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.MON_END_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'MON_END_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.MON_END_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal TUE_START_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.TUE_START_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'TUE_START_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.TUE_START_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal TUE_END_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.TUE_END_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'TUE_END_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.TUE_END_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal WED_START_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.WED_START_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'WED_START_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.WED_START_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal WED_END_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.WED_END_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'WED_END_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.WED_END_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal THU_START_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.THU_START_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'THU_START_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.THU_START_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal THU_END_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.THU_END_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'THU_END_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.THU_END_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal FRI_START_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.FRI_START_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'FRI_START_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.FRI_START_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal FRI_END_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.FRI_END_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'FRI_END_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.FRI_END_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SAT_START_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.SAT_START_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'SAT_START_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.SAT_START_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal SAT_END_TIME {
                get {
                    try {
                        return ((decimal)(this[this.tableInstallationSlots.SAT_END_TIMEColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'SAT_END_TIME\' in table \'InstallationSlots\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableInstallationSlots.SAT_END_TIMEColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSITE_IDNull() {
                return this.IsNull(this.tableInstallationSlots.SITE_IDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSITE_IDNull() {
                this[this.tableInstallationSlots.SITE_IDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTIME_SLOTNull() {
                return this.IsNull(this.tableInstallationSlots.TIME_SLOTColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTIME_SLOTNull() {
                this[this.tableInstallationSlots.TIME_SLOTColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSCHEDULE_DATENull() {
                return this.IsNull(this.tableInstallationSlots.SCHEDULE_DATEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSCHEDULE_DATENull() {
                this[this.tableInstallationSlots.SCHEDULE_DATEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSUN_START_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.SUN_START_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSUN_START_TIMENull() {
                this[this.tableInstallationSlots.SUN_START_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSUN_END_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.SUN_END_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSUN_END_TIMENull() {
                this[this.tableInstallationSlots.SUN_END_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMON_START_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.MON_START_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMON_START_TIMENull() {
                this[this.tableInstallationSlots.MON_START_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMON_END_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.MON_END_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMON_END_TIMENull() {
                this[this.tableInstallationSlots.MON_END_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTUE_START_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.TUE_START_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTUE_START_TIMENull() {
                this[this.tableInstallationSlots.TUE_START_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTUE_END_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.TUE_END_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTUE_END_TIMENull() {
                this[this.tableInstallationSlots.TUE_END_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWED_START_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.WED_START_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWED_START_TIMENull() {
                this[this.tableInstallationSlots.WED_START_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWED_END_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.WED_END_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWED_END_TIMENull() {
                this[this.tableInstallationSlots.WED_END_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTHU_START_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.THU_START_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTHU_START_TIMENull() {
                this[this.tableInstallationSlots.THU_START_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTHU_END_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.THU_END_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTHU_END_TIMENull() {
                this[this.tableInstallationSlots.THU_END_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFRI_START_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.FRI_START_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFRI_START_TIMENull() {
                this[this.tableInstallationSlots.FRI_START_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFRI_END_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.FRI_END_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFRI_END_TIMENull() {
                this[this.tableInstallationSlots.FRI_END_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSAT_START_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.SAT_START_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSAT_START_TIMENull() {
                this[this.tableInstallationSlots.SAT_START_TIMEColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSAT_END_TIMENull() {
                return this.IsNull(this.tableInstallationSlots.SAT_END_TIMEColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSAT_END_TIMENull() {
                this[this.tableInstallationSlots.SAT_END_TIMEColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class InstallationSlotsRowChangeEvent : System.EventArgs {
            
            private InstallationSlotsRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InstallationSlotsRowChangeEvent(InstallationSlotsRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public InstallationSlotsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591